### PR TITLE
Lesson 5 comments Tomi

### PR DESCRIPTION
**Pull request by tomicapretto**
Really enjoyed reading through the lesson. Your narrative is so good Alex! You're great at creating stories.

Let me drop some high-level comments here. You'll find more in-depth comments in the notebook itself.

* In general: 
	* Make sure to have appropriate labels on all charts
	* Figure size. There's an "official" size we were using in Lesson 2. I do think it's a little large for a notebook. But we should have something consistent across all lessons. I'm open to having a different figure size of course.
	* Write the statistical formulation of the model.
		* We don't need to describe them in full detail all the time, but it's good to have them because it's there where the subtle details pop up.
		* I'm glad to help or review this part :)

* About the models
    * I still need to check the mathematical details of the last models. The parameter recovery was not so good in one case, but I couldn't check the model yet. Also, I saw your comment about the recovery when using pivot with PyMC. I'll review it in the following days.
    
**About this PR**

Do whatever you want! :D Feel free to read the comments and close, or merge with your branch... whatever works for you to incorporate the feedback.

### CODE REVIEW

**Comment by tomicapretto** [comment]
<p>Sectio 22.1 of the Kruschke's book has an example. Is too mathy for the course I think but it's a starting point.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/16/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Tomi, wil students have been taught <code>include_mean=True</code> at that point in the course? </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/16/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Actually this isn't what we want here, because <code>winning_topping_mean</code> will also have `<code>winning_topping_obs</code> as dimension, which is not what we want here </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/16/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
@AlexAndorra feel free to close this whenever you want :)

**Pull request closed without merging**
