### PR TITLE
Lesson 04 Record ready

### PR DESCRIPTION
**Pull request by canyon289**
Building on https://github.com/tomicapretto/etc/pull/2 with goal to make make this record ready

### CODE REVIEW

**Comment by tomicapretto** [comment]
General question, are we using `black` or a similar formatting tool?

**Comment by canyon289** [comment]
<p>So its moreso that my joke might not be as funny as I thought. I reworded to make it more apparent its a congrats on a new job at a video game store. If it still doesnt work though I'll remove it :'(</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Im not a fan of imported without the module namespace because then its hard to tell where a function came from. I'm not strictly fixed on this point, but should be consistent.</p><p> </p><p>Leaving open for now until your response and then after that well have a decision </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>yes added </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Added </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Thanks</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Agree</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Changed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Thanks</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Ah, this seeems to be a bug in reviewnb. It right when viewed locally</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Rephrased</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>"So far we've only worked with boolean data, meaning it can only take on one of two values"</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Ah good catch</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>fixed </p><p> </p><p>Linear regression makes predictions that range from negative infinity to positive infinity. What if we can remap our observed to be between 0 and 1?</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Agreed, leaving this one open so we dont forget</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>This sigma is larger? Should I set a different prior?</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Im confused as I dont define <code>p = pm.Deterministic("p", pm.math.sigmoid(mu))</code></p><p> </p><p> </p><p>What should the fix be?</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>I added this but there seems to be bug when I make predictions, in that the model var names no longer correlate with idata? I cant debug more later, noting for now as I need to head to bed. If you have any ideas let me know</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
Thanks for the review @tomicapretto. I could use opinion on plot_cap

I could use your guidance on
* Setting the alias on model vars and then making future predictions. Its causing an issue with prediction code but im not sure if its a bug
* What do I need to do specifically for the `p` in the binomial model

**Comment by tomicapretto** [comment]
<p>Oh no! There's a high chance I'm bad at understanding this type of jokes. Maybe if we add "Congratulations on your new job! In this lesson we are all data scientists..." that would make it clearer (at least to me) that I (as a student) will be working as data scientist at a video game shop.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I agree with your comment, but I think <code>plots</code> is too general.  What about <code>import plots from bambi.plots as bmb_plots</code>?  </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Haha thats ok. its why you and alex are on the course together. The jokes will average out to be juuussttt right</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Sold ill make the change in next 24 hours</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Awesome</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I mean, the sigma not being used in the model</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Yeah, maybe it's a bug in the  implementation.  I'll try to check on my side later.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>That happens in </p><p> </p><pre class="ql-syntax" spellcheck="false">with pm.Model() as logistic_regression_model:
    
    # This is all the same linear regression as before
    sigma = pm.Normal("p_convert", 1)
    β = pm.Normal("β", 0, 1, size=2)
    
    mu = pm.Deterministic("mu", β[0] + β[1]*df["age"])
    
    # Our is our new sigmoid transformation
    p = pm.Deterministic("p", pm.math.sigmoid(mu))
    
    # Switch to Bernoulli because we're predicting individual observations
    obs = pm.Bernoulli("obs", p=p, observed=converted_bool)
    idata_sigmoid = pm.sample()
</pre>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>It would be good to sort the order of the imports as well.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>It still says "age_buckets". Do you have any strong opinion to have that instead of "Age groups"?</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
I think the lesson is finished codewise, but it still needs more work in terms of the explanations of what's going on. I can understand everything and I see the logic between each of the steps (and it all makes sense) but I think there are still many empty gaps for people that are learning these concepts. 

I think I'm a little biased towards being technically exhaustive all the time and that's not the best in all cases because it makes things much denser. So between you and me, I think we will find the right balance :D

**Comment by AlexAndorra** [comment]
<p>Also make sure to explain in the video that all the probability scale ranges from -4 (0 prob) to +4 (1 prob), with 0.0 corresponding to 0.5 prob. Really helpful to develop an intuition of where we are in the prob scale from the real scale</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Reviewed until the Bambi part @canyon289 . Going for a quick run and gonna review the rest afterwards 😉

**Comment by AlexAndorra** [comment]
Review finished @canyon289 ! What an awesome lesson, really enjoyed it!
This sets up me nicely for Categorical regression, and I'm pretty you'll like how this fits well with this lesson (first version of my NB coming really soon 🥁 ).
I left a few comments. I think we're almost there

**Comment by canyon289** [comment]
thank you. I'll get this lesson fixed up this week

**Comment by tomicapretto** [comment]
<p>Haven't noticed this but I agree with your point. I think we can come up with a rounded version of the edges such as (min, 25], (25, 40], (40, 50], (50, 60] for example.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>It's a tranformation builtin Bambi. It basically standardizes 'age' to be mean 0 and sd 1. But the good part is that it keeps the original values it used to standardize, so when you need to predict on new data, the appropriate transformation is applied.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>The party_id[Democrat] is the Intercept. We should use +0 in the formula to remove that so it appears the party_id[Democrat]</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed!</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Changed, Thank you both</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Writing down the model is a good idea as youll be doing that in the previous lessons and we should be consistent throughout this whole course. I appreciate you adding these</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Agree thank you!</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Noted</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>You shouild I think change this to mu instead of using eta then? I think thatd be more intutive tbh</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Tomi, will you be explaining +0 in lesson 3?</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Note ill add a reminder here as well, but want to undertand if this is the first place it will show up</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>added an explanation</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>:'( they are crying</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Completed (and pushed)</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
@canyon289  I'm going through the last review of the lesson in presentation mode. I'm leaving final comments here:

1. I think the following text is not part of the slide, but it's there accidentally.
image

2. Figure size. I think it would be better to have a global `FIGSIZE` variable you can use in most places.
image


3. Not sure if you want to show the code here or just the figure
image

4. Text
image

5. Are the two colors intentional? I'm neutral to it. Just double-checking. And being nitpicky, as usual :sweat_smile: 
image

6. Looks like there's content missing before Slide 56
7. I think the content is right but the title is not, since it's not needed to create that machine anymore
image
8. Some details to adjust here
image

---

As you can see, the points refer to things you would have realized on your side when recording. I just wanted to highlight them since I was already reviewing the content, it cost me nothing to post them here.

I want to emphasize how much I like the story you propose for this lesson. All the conversation with the boss and how it brings new stuff to learn in the lesson is fantastic. I think you did an awesome job here. Congrats!!

**Comment by canyon289** [comment]
we did it together and you individually are amazing. getting all detail right now makes recording smoother, smooth records create very high quality course, and a high quality course means a great contributor experience!

I will get all this fixed and get the recording started in the next five days. 

thank you much

**Pull request closed without merging**
