### PR TITLE
Add Lesson 3

### PR DESCRIPTION
**Pull request by tomicapretto**

### CODE REVIEW

**Comment by canyon289** [comment]
Lesson is approved from my end. @AlexAndorra can review if he likes as well

You're ready to record. Lesson recap section is not complete yet but that can be done in parallel with recording

**Comment by canyon289** [comment]
Also notebook needs to be slidified so there may be some slides that need tweaking to fit on the screen, but again not every slide needs to fit on the screen. Scrolling is fine but use it sparingly if adds to the explanation.

Super great work

**Comment by tomicapretto** [comment]
Writing the lesson recap I found there's a question I left, it's about the subtitle of Section 80

```
# Section 80: Understanding encodings

**Any preference or suggestion for the subtitle?**

* Making math possible with categories
* How to map categories to numbers
* Mapping categories to values
* From categories to numbers
* Making sense of restrictions
```

**Comment by tomicapretto** [comment]
> Lesson is approved from my end. @AlexAndorra can review if he likes as well
> 
> You're ready to record. Lesson recap section is not complete yet but that can be done in parallel with recording

Just completed the lesson recap. What's left is

* [ ] Appendix I: Priors in Bambi
* [ ] Exercises
    *  I do have a bunch in `Ideas.ipynb`

**Comment by canyon289** [comment]
This is my favorite
* Making math possible with categories

For appendix and exercises feel free to defer those till after doing recordings

**Comment by canyon289** [comment]
@AlexAndorra Ensure lesson 5 runs with this new environment before recording

**Pull request closed without merging**
