### PR TITLE
Three

### PR DESCRIPTION
**Pull request by tomicapretto**

### CODE REVIEW

**Comment by canyon289** [comment]
@tomicapretto I started looking through this but couldnt quite figure out where the section breaks were. I also couldnt find that markdown file you were showing me the other day. Could you add that here so were referring to the same thing? That 'll help me help you build out this lesson
. 
https://github.com/IntuitiveBayesInternal/AdvancedRegressionInternal/blob/main/scripts/lesson_03.md

**Comment by tomicapretto** [comment]
> @tomicapretto I started looking through this but couldnt quite figure out where the section breaks were. I also couldnt find that markdown file you were showing me the other day. Could you add that here so were referring to the same thing? That 'll help me help you build out this lesson . https://github.com/IntuitiveBayesInternal/AdvancedRegressionInternal/blob/main/scripts/lesson_03.md

The file is a Jupyter Notebook (not Markdown) `lessons/03_Bambi_Introduction/Ideas.ipynb`

**Comment by canyon289** [comment]
Got it, in that case please add all section headers and section recaps, even if incomplete, so its easier to navigate the notebook. i can then more seamlessly start filling things in

**Comment by tomicapretto** [comment]
> Got it, in that case please add all section headers and section recaps, even if incomplete, so its easier to navigate the notebook. i can then more seamlessly start filling things in

Except from the last section and the appendix, most of the bulk of the content is there. In many cases rich explanations are provided as well. Do you prefer to start reviewing now, or only once all sections are done?

**Comment by canyon289** [comment]
Ill review now to save you the hassle of updating a completed notebook. Give me 24 hours

**Comment by canyon289** [comment]
Overall amazing!!! left my comments here https://github.com/tomicapretto/etc/pull/14

Section 60 and 70 will be the most challenging as theyre packed with information but thats not a bad thing. Its sections like those, that when we get right, make the course exceptional.

To get this to code complete
*  we really dial in section 70 with code (with a couple minor additions in other sections) 
* Add all section recaps
* Finish section 100 (though thats lower priority as its straightforward)


We that I think we're good to go on expanding this lesson with images, memes etc.

**Comment by canyon289** [comment]
Left comments throughout. Biggest thing
1. Need to reduce the bulelst point only sildes and add with something more visually interesting. The talking points are good, now leverage our visual medium
2. Section 60 can be split into 2 and needs a bit more work to be intuitive

Other than that the last sections generally need development.

If we continue working on it together at this pace, and have a working meeting or two, i bet we can get this done in one week

**Pull request closed without merging**
