### PR TITLE
2 - Record Ready Notebook

### PR DESCRIPTION
**Pull request by tomicapretto**

### CODE REVIEW

**Comment by canyon289** [comment]
Now that were at this stage I want to provide an exhaustive list of what we look for. The list is long but just like code style, docstyle, and linting after a few PRs it becomes automatic. Listing here so you can ask any questions, or challenge any that don't make sense!

## Visual Style
* Fully slidifed so we can present in rise in 1920 x 1080
* All figures have labels that are readable
* Figures aren't cut off
* Low amount of text only slides
* Low amount of text on text only slides

## Speaking notes
* Speaking notes are available for us to read
  * and for students to read

## Narrative and Lesson Chunking
* Lesson slides have `# header` `## subheader`
* Single slide with a single point
* A balance of technical content, and "breather" content to tie it all together
  * Getting this right is one of the hardest parts
* Section recap

## Resources
www.freepik.com - For pictures

**Comment by tomicapretto** [comment]
@canyon289 I could finish up to the "Adding a slope" section. I'll keep working on this tomorrow. Could you review what's done so far? In particular, I would like criticism about narrative, terminologies used, etc. Of course, add anything else you feel necessary.

**Comment by canyon289** [comment]
definitely will do

**Comment by tomicapretto** [comment]
Closing this one in favor of a new one

**Pull request closed without merging**
