### PR TITLE
Add prod-ready lesson 5 NB

### PR DESCRIPTION
**Pull request by AlexAndorra**
- Ready for review
- Still a first version:
    - Need to add / improve explanatory text
    - Check correctness and interpretation of the pivot models

### CODE REVIEW

**Comment by canyon289** [comment]
Looked over it quickly and overall its looking nice. Will review at code grade given narration and memes and whatnot are not there yet

**Comment by canyon289** [comment]
Partially reviewed, will provide much more indepth review in next couple of days

**Comment by canyon289** [comment]
<p>We also dont have prior and posterior comparison plots anywhere else in the course yet. Do you think we should add them Tomas to earlier lessons? If we introduce them here it begs the question why we didnt use them earlier</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
Comments from a much more indepth review.

Notebook is at rough code grade albeit missing the last real world section.

https://github.com/IntuitiveBayes/AdvancedRegressionInternal/blob/main/scripts/lesson_05.md

Here's what I see as next steps

## 1. Define Lesson structure
Copying from the comment
```
    Categorical no covariates, introducing softmax
    Overparameteriztaion and pivot
    ZSN
    Bambi models
    Real world example\
```

## 2. Explain overparameterization, pivot and ZSN super well
Explaining overparameterization, and then how pivot and ZSN fix it will be the key to this lesson. Right now the code is there but even from the text I'm not convinced what overparameterization, 

## 3. Breaking down the technical complexity
* Show a softmax function written in numpy showing how it bounds classes
* Show the math between pivot and ZSN outside of PyMC and explain what its doing in regression
* Tie these back to lin reg, even showing a sampling calculation for both in numpy of how PyMC constructs the underlying regression

## 4. Ensure all elements are supported by a narrative
With so much going on in this lesson, my prior is we should pick a story thats something like "Were in an international crepe competition so everything needs to be ranked, but because Im Alex and I'm french and I like nutella I want that to win, but Thomas is german and likes sugar so he wants that to win so were going to pay extra attention to that.

That way when we write plots we can show the big plot, but then subset to those categories for the detailed explanation

**Comment by AlexAndorra** [comment]
@canyon289 @tomicapretto this is ready for review again. The simulated data part is ready, nonwithstanding some TODOs that I marked and welcome your input and ideas on.
I'm gonna start working on the Estonian data part right now, but for simplicity, we can merge this PR once we all agree on the current content. I'll open a new PR for the "real data" content

**Comment by canyon289** [comment]
opening new pr sounds great. thank you Alex will review

**Comment by canyon289** [comment]
@AlexAndorra Which one should we review? Theres two notebooks


image

**Comment by AlexAndorra** [comment]
`lesson_05` @canyon289

**Comment by canyon289** [comment]
Oh man I just got what the other notebook title was. Mate (the drink) for the win!

**Comment by AlexAndorra** [comment]
Ha ha ha, yessss!

**Comment by AlexAndorra** [comment]
Aaaaand, this lesson is now entirely done and ready for review @canyon289 @tomicapretto 🍾 
In parallel to incorporating your feedback, my next steps are:
- Write lesson 5 exercises and solutions ([outline](https://github.com/IntuitiveBayesInternal/AdvancedRegressionInternal/issues/104))
- Move on to lesson 6 (multinomial regression)

**Comment by canyon289** [comment]
<p>Figure is too big</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I did that to have at least an example with a continuous predictor. Otherwise, it's only gonna be categorical ones</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>We could do a latex slide in Jupyter, and have Fadi animate it as I talk over it?</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>They are already. I recommend reviewing this lesson in slide mode, everything is ready for it</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Sounds great</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>But here I don't want to compare two different categories. I wanna see if we recover the true values for <em>each</em> category. For comparisons, I think forest plots are really great </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
Upfront I'm going to be a bit nit pickier than the intro course. There was feedback in the intro course that it was obvious three people all with subtly different styles put the course together, and while we dont need to be exactly the same there some small stylistic things we can do consistent


Story and code wise this is amazing.  I may have some minor suggestions but nothing major at this point.

**note**: There are some areas I can see you add your twist and are amazing, the feedback right now is biased towards changes as I want to get those to you! Fantastic job, im so excited for this

# general stylistic comments
1. Use `## Title` more often. Not every slide needs it but more than we have now.
  * For example section 4 has no headers on its slide. 
  * Section 5 is another example. From just the slides we cant tell the story. Having titles would help, especially as theres a lot of visual real estate were not using
  * The secondary benefit of this is it makes navigating the notebook easier as it creates the TOC tree in jupyter
  * **specific action**: Remove anything lower as it just makes the text smaller and in slides we don't need the visual hierarchy that we do in long markdown document
3. Lets see if we can get hide code working, as its well be using a different version than package we installed last time
4. Resize plots and gifs to fit screen 1920x1080 screen size better
  * Pixel height of 750 has worked well


## Figures should be sized to take up most of screen, add `## header`
image

## Header title and one subtitel

For title slides of sections do
```
# Section title
Some clever thing
```

```
# Intercept only Categorical regerssion
Introducing a new link function and likelihood
```
Then on the next silde keep the bullet points

```
# The grand reveal
* The **Categorical distribution** (which is an n-dimensional Bernoulli)
* The **softmax link function** (which is an n-dimensional logit)
```

image

## Hide code
I know this wasn't working for you in last course. Lets try it

image

## Some plots are too big
Where we can try and avoid scrolling. 
image

## Some are too small
Make the gifs bigger
```
<img src="https://media.giphy.com/media/xULW8PeN7fq3IYJH7a/giphy.gif" style="margin:auto; height:750px;"/>
```
Heres the tiny one
image

Here it is bigger 
image



## Download gifs to repo rather than link them out
Links die, we want our material to be self contained. Download them and use a local referenec

## All images must be copyright free. Gifs we can make ignore
I havent checked

## Center images
instead of using `![]` markdown syntax there is an html block we use that makes things consistent. I'll add a second comment shortly on what that block is
image

## Hide code and warnings
You've noted this already, hide the code. We can suppress the warnings as well, this one is way too distracting
image

## Lesson recap incomplete
image

**Comment by canyon289** [comment]
Heres the code for images and gifs to center and resize them
```
<center>
  <img src="imgs/PrintingRevolution.jpg" style="height:750px"; />
</center>
```

**Comment by AlexAndorra** [comment]
<p>But then it's not really a continuous variable, isn't it (I think it's called truncated data)?</p><p>I'm ok with just doing <code>np.random.normal(35, 10, 10)</code>, but I find value in showing an example with standardized data, because it's unfortunately a case I often see in real life (people sharing standardized data instead of the raw one)</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Integrated your comments @canyon289 @tomicapretto 🍾

**Comment by canyon289** [comment]
Again great job with the narration, code, examples etc. All thats left are minor nits on formatting.

## H1 CSS needs to be fixed
This is on me, Both lines should be blue. Once youre done with the notebook I'll push a new rise css file that'll fix this
image

## Many images are too big
A couple images here and there that are bigger than the screen size are fine. Theres many in this notebook though. 
The two reasons we should avoid this are
1. Its hard for people to take in the whole image when its cutoff and were scrolling to show it
2. It means reediting is harder if we need to rerecord or change a portion of the image.

image

**Comment by AlexAndorra** [comment]
<p>Sounds good, will update</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Good idea, will do</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p><p> </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Integrated second wave of comments @tomicapretto @canyon289

**Comment by canyon289** [comment]
Really great stuff Alex. Approved on my end with some minor comments below

* Thanks for adding real world stuff from your podcast! Be sure to add those to the lesson references
* One slide per section is great. Thank you!
* Narration and gifs are great
* You break up this lesson quite well
* Showing multiple approaches while tricky, is done quite well and adds an interesting twist to this lesson
* Your narrative notes and styling to emphasis key points is really great
* The animation notes you added I agree with, Thanks for taking full advantage of our video format

## Things to change
Good news! Its all very minor


* Need to turn autoselect off in notebook. I can do that right before you record
* Some slides are cutting off on my screen very slightly like the one below, but maybe theyll fit on your screen. After you check with Fadi that the recording is 16:9 ensure these labels fit
* This is one me, I need to get you an updated CSS file where both lines of the header are blue (not blue black)
* For posterior of national effects (the first time) be sure to explain why our model as a problem. What is it that you're seeing?
  * We can also then have fadi highlight it on the screen so folks know. Great job including something thats wrong as folks have been asking for that!
  * Similar one we get to fixed version (on slide 87) be sure to say, or have fadi highight, the good ones and bad ones, 
* A couple of slides, like slide 120, would be better if we hide the code, but I also recall you saying its hidden on your side so it must be that were using different plugins or something. We can debug sometime later. Nothing major

image
image
image
image
image

**Comment by AlexAndorra** [comment]
Thanks @canyon289 !

> Some slides are cutting off on my screen very slightly like the one below, but maybe theyll fit on your screen. After you check with Fadi that the recording is 16:9 ensure these labels fit

Two questions about that:
1. Can you send me the link of the tool that you seem to be using and that gives you the resolution of your screen in the top-right corner?
2. How do you make the plots fit your screen if they do not? Change `figsize`

> A couple of slides, like slide 120, would be better if we hide the code, but I also recall you saying its hidden on your side

Yeah code is already hidden

**Comment by canyon289** [comment]
I use firefox, theres a sccreen size ruler. Figsize is the way to adjust

https://firefox-source-docs.mozilla.org/devtools-user/rulers/index.html

**Comment by tomicapretto** [comment]
<p>I think this is a good idea.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
@AlexAndorra the comments I left are all minor details. Perhaps except for the one bout the "predictive" vs "retrodictive" which makes me think if I should change the term in Lesson 3 as well. 

I really like the lesson. There are very important topics that are very well explained, and that's extremely important. Also, you show how you work in the real world and that's also very valuable. 

Perhaps we can discuss tomorrow screen sizes, image sizes, etc. But that's a detail that we'll figure out.

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Ha ha right, I didn't even notice that!</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Good catch, thanks</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/11/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
All done, thanks a lot guys 🍾

**Pull request closed without merging**
