### PR TITLE
L2

### PR DESCRIPTION
**Pull request by tomicapretto**
Current WIP is Intercept-only regression (everything before that is ready for review)

### CODE REVIEW

**Comment by tomicapretto** [comment]
@canyon289 @AlexAndorra  I think this is ready for review. Both of the code and also some of the narrative which is there.

**Comment by canyon289** [comment]
thanks I'll review in next eight hours. quite excited to do so

**Comment by canyon289** [comment]
@tomicapretto overall comments

For code notebook standards this is really good. In a couple of places in the section i would show
* More HDI plots, such as in the averaging section
* az.plot_posterior() plots as they include HDI, mean etc.
  * The notebook is very plot trace heavy right now

In terms of key points everything is there. In this one notebook as things are review in a couple of spots we can add a couple of reminders explicitly like. "Sampling from posterior predictive", or "Checking diagnostics to ensure MCMC converged"
nothing too major.

In terms of tone its very warm and encouraging. Its a great start to building out the narrative slides. In some sections ilke Section 20, and  70 the narrative points are listed all at the front and we just need to weave them in throughout more slides and order them correctly in the section but that'll be quite easy because we know **what** we want to say, we just have to figure out **where** and **how**

**Comment by tomicapretto** [comment]
<p>Thanks! </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Really like it. Thanks a lot!</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Thanks for the suggestion. I agree this should be multiple slides, with different images and bullet points. </p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Makes sense</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I agree showing a flat line is the way to go. But what variable do we use as predictor? We can pick Length, which is what we use later. But to do so we should first tel somewhere that we'll get started by using Lenght as predictor so when we show this chart it's not like it comes out of nowhere.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I'm not sure I understand. With "adding dots" I imagine some dummy data, and not the real data, so we use the model to fit the lines to the real data. Let's discuss today.</p>

---

 <a href='https://app.reviewnb.com/tomicapretto/etc/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
> @tomicapretto overall comments
> 
> For code notebook standards this is really good. In a couple of places in the section i would show
> 
> * More HDI plots, such as in the averaging section
> * az.plot_posterior() plots as they include HDI, mean etc.
>   
>   * The notebook is very plot trace heavy right now
> 
> In terms of key points everything is there. In this one notebook as things are review in a couple of spots we can add a couple of reminders explicitly like. "Sampling from posterior predictive", or "Checking diagnostics to ensure MCMC converged" nothing too major.
> 
> In terms of tone its very warm and encouraging. Its a great start to building out the narrative slides. In some sections ilke Section 20, and 70 the narrative points are listed all at the front and we just need to weave them in throughout more slides and order them correctly in the section but that'll be quite easy because we know **what** we want to say, we just have to figure out **where** and **how**

Thanks a lot for the detailed feedback. It's true I'm using `az.plot_trace()` too much and not `az.plot_posterior()`. It makes sense to use the latter more. Also, you're right when you suggest mentioning "sampling from posterior predictive" or "checking diagnostics". The notebook needs to pay a little more attention to that.

**Comment by canyon289** [comment]
Start moving into productionized slides

**Comment by tomicapretto** [comment]
Agreed with @canyon289 we close this one and open a new one so we start a fresh review process.

**Pull request closed without merging**
